kind: Service                     
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 80                              
      targetPort: 80                  
  selector:
    company: gslab
  type: NodePort
